---
# Ignores all words with total frequency lower than this. For smaller
# corpora a smaller min_count will be necessary.
min_count: 50

# Merges topic vectors which have a cosine distance smaller than
# topic_merge_delta using dbscan. The epsilon parameter of dbscan is
# set to the topic_merge_delta.
topic_merge_delta: 0.1

# Add phrases to topic descriptions.
# Uses gensim phrases to find common phrases in the corpus and adds them
# to the vocabulary.
# For more information visit:
# https://radimrehurek.com/gensim/models/phrases.html
ngram_vocab: false

# Pass custom arguments to gensim phrases.
ngram_vocab_args: null

# This will determine which model is used to generate the document and
# word embeddings. The valid string options are:
#
#  * doc2vec
#  * universal-sentence-encoder
#  * universal-sentence-encoder-large
#  * universal-sentence-encoder-multilingual
#  * universal-sentence-encoder-multilingual-large
#  * distiluse-base-multilingual-cased
#  * all-MiniLM-L6-v2
#  * paraphrase-multilingual-MiniLM-L12-v2
embedding_model: doc2vec

# Pre-trained embedding models will be downloaded automatically by
# default. However they can also be uploaded from a file that is in the
# location of embedding_model_path.
# Warning: the model at embedding_model_path must match the
# embedding_model parameter type.
embedding_batch_size: 32


